language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to run tests
before_script:
  mkdir -p shippable/codecoverage
  mkdir -p shippable/testresults
  

script:  
  py.test --cov-report xml --cov openpyxl --resultlog=shippable/testresults
install:
  pip install lxml pytest nose

script:  
  py.test
