language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  pip install lxml pytest nose pytest-cov

before_script:
  mkdir -p shippable/codecoverage

script:  
 
  - coverage run py.test
  - coverage xml -o shippable/codecoverage/coverage.xml p
