language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  pip install lxml pytest nose pytest-cov 

before_script:
  mkdir -p shippable/codecoverage shippable/testresults

script:  
 
  - coverage run py.test
  - coverage xml -o shippable/codecoverage/coverage.xml 
  - nosetests openpyxl/openpyxl/cell.py  --with-xunit --xunit-file=shippable/testresults/nosetests.xml
